[tool.poetry]
name = "llm-writer"
version = "0.1.0"
description = ""
authors = ["wangboyu89 <wangboyu89@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "4.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
